name: flutterial_components
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: rxlabz <email@example.com>

environment:
  sdk: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
