name: panache_lib
description: Panache app core
version: 0.1.0
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/panache

environment:
  sdk: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  path_provider: any
  string_scanner: any

dev_dependencies:
  flutter_test:
    sdk: flutter
