name: flutterial_components
description: A starting point for Dart libraries or applications.
version: 0.0.2
author: rxlabz <rxlabz@gmail.com>

environment:
  sdk: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  path_provider: any
  string_scanner: any

dev_dependencies:
  flutter_test:
    sdk: flutter
